# Generated by Django 4.2 on 2023-04-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('description', models.TextField(verbose_name='Описание сайта')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Ссылка на linkedin')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Ссылка на twitter')),
                ('skype', models.URLField(blank=True, null=True, verbose_name='Ссылка на skype')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Ссылка на telegram')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Ссылка на whatsapp')),
            ],
        ),
    ]
